# Generated by Django 2.0.6 on 2018-06-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='twitchUsername',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
